language: node_js
node_js:
- 5.2.0
install:
- npm install
script:
- webpack
sudo: false
deploy:
- provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_KEY"
  on:
    tags: true
env:
  global:
  - secure: 8rs6l6GNxktkB1lA1ej/7/zUeHb2iu/UFQtYJ6MFpOx/tlLEEkrljq7aMwRhitVTFQfm2Vt/+5D2cSkSXh4HmLF269IplBeOhPBHO6U0IickBvR1Dx+bayqGBbnv6MIlMgIX0Gb8oPBo+yqPj3899DQdwSRLORP/dFDuUsQPkyLnYw6ab8Z1kzxSunNf/m10+5gBvvwv1o7FN2IB52VYCg1h3yyCwkQWNgXHq1ShmPsGfTPqGF9xcKsGkHMLH5z5wLRvu/dVtjeLW/6AToMuuy5BrZ8xSTdrOUGCQOWSSg//I9nYGCjYcPYuGbifTvr8RkcB47hjyziZ1FhvjONzCpmo0qoUVMZuvxNU8iAEFAnTLT/FYlCmIWOoGCb77gKynP/M5rYdZIIHDH57pRX1QMyNc0O0RkuMr3ZkCyYDccj9BzFnG/s3dqSWqO/wJYwjdW6lFRrXA8ysEmkHV+cTxCnbr+C79h51hS+XPEshoZWQQCVE2AAqpfdjzLsR3V6sTkm6edobdrpUhOmdSnvipZYW//lBxof6nCCK3wYtkS+FheupBzaPA692pxYsEg950mLDVja41INs+JDiVYx2KIGFPYX0PVxxmtovV8lxjqcwak/dosjxYs3k+Rq05EG1RVGXcM0Hkt8wMHm07D/qIKbAF3b+VQWwAugMF16qE5E=
  - secure: WltfYTUH2q/KZaaY21hONhIbcWPM+WfZkRfPHySewO2HD9eiQ8BJBlbhHSjrBeaR3y3ExeFIRubHQAX1W4bCF7ViTZE0rXso5f04BCWYdjnhT8Q0Zt/PHYyBrJK4tyos5iB+ntt3pHlX9eRHJBWxewUatRWStl/C0lWbIuG0ORCJTYxQDLBjkz/Q4FMs/bFfdFd0gjypa3TH2X01mxt55frP0LvDvRoZFx6DS+eByPatnhizb7oikQ0jWBRECFRRkBw2qVXxRiESnHZ3GWpkFr6bWEWRNljCWPmh/LtCs88l1uT8bFCGA9DrqcHab9l9YjqSF+DMn/gx7oAwDP1dEDf9JfvFW0NkrabQ4fjd/g8rr0cy13dvQkxak4w+Ie5yvrDELrF8h+Q8tnNFf3qLHM8XkiwpRBVHuI69JbpwaEedi7GZuKa/tK7joSU4pfKDtNoQZgP1/x4T9+qAS9MNdZDlexdr0d2wqacqChPCE44qUB1DG5RIv4peH777xXGVF2nQwKZa4jShWKSwOusi0RxESRcYoStWEhDI7cq7jdV4BZqB1yhiLpXdBxx3OXpIWwTpWDhJ6Heivuv/xPtlB7x2mA9G+M5LX5gCHKlsqvQTPi1S660iKRYYTyKNdoTH6npyXLI819tmdUJWOU8injon7666jVaApmhhG0FtLnI=
